//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/GameDevHQ/FileBase/Projects/Tutorials/Starter_Files/Input_System_Starter_File/Game/Scripts/Player/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""cbec9006-6cc3-4d9d-a61b-9249785eb458"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""1b3b4043-a0c5-47d1-9cb9-b75ce1bd95b9"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""InteractableButton1"",
                    ""type"": ""Button"",
                    ""id"": ""73daa6b3-370d-47ad-912e-fc17874b08be"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InteractableButton2"",
                    ""type"": ""Button"",
                    ""id"": ""34e0f906-5d86-4345-a46e-ba1d61eb4e91"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InteractableButton3"",
                    ""type"": ""Button"",
                    ""id"": ""4fe36cf1-8aed-4bdc-90ce-e31a6940a8e9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""3D Vector"",
                    ""id"": ""bc8871d9-a3cd-4c24-9ce3-f3749fb87b1a"",
                    ""path"": ""3DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""1c1b7c3b-4317-47fc-8151-5e6a07a279d5"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""75b37c6c-ba86-4433-92b6-b0b291a06f22"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""forward"",
                    ""id"": ""24006f07-8d7b-4018-a22e-b8cba89df5a0"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""backward"",
                    ""id"": ""1a59257c-ad4f-48f7-a971-802d7616b27b"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""30163681-f874-4d6c-bf84-90ddcfe0b6f8"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InteractableButton1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f1293406-bc99-4f56-b1af-78b18a64cbae"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InteractableButton2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1dde5e24-be56-477b-97fb-4aeb6f104e24"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InteractableButton3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Movement = m_Player.FindAction("Movement", throwIfNotFound: true);
        m_Player_InteractableButton1 = m_Player.FindAction("InteractableButton1", throwIfNotFound: true);
        m_Player_InteractableButton2 = m_Player.FindAction("InteractableButton2", throwIfNotFound: true);
        m_Player_InteractableButton3 = m_Player.FindAction("InteractableButton3", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_Movement;
    private readonly InputAction m_Player_InteractableButton1;
    private readonly InputAction m_Player_InteractableButton2;
    private readonly InputAction m_Player_InteractableButton3;
    public struct PlayerActions
    {
        private @InputActions m_Wrapper;
        public PlayerActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Player_Movement;
        public InputAction @InteractableButton1 => m_Wrapper.m_Player_InteractableButton1;
        public InputAction @InteractableButton2 => m_Wrapper.m_Player_InteractableButton2;
        public InputAction @InteractableButton3 => m_Wrapper.m_Player_InteractableButton3;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @InteractableButton1.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInteractableButton1;
                @InteractableButton1.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInteractableButton1;
                @InteractableButton1.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInteractableButton1;
                @InteractableButton2.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInteractableButton2;
                @InteractableButton2.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInteractableButton2;
                @InteractableButton2.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInteractableButton2;
                @InteractableButton3.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInteractableButton3;
                @InteractableButton3.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInteractableButton3;
                @InteractableButton3.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInteractableButton3;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @InteractableButton1.started += instance.OnInteractableButton1;
                @InteractableButton1.performed += instance.OnInteractableButton1;
                @InteractableButton1.canceled += instance.OnInteractableButton1;
                @InteractableButton2.started += instance.OnInteractableButton2;
                @InteractableButton2.performed += instance.OnInteractableButton2;
                @InteractableButton2.canceled += instance.OnInteractableButton2;
                @InteractableButton3.started += instance.OnInteractableButton3;
                @InteractableButton3.performed += instance.OnInteractableButton3;
                @InteractableButton3.canceled += instance.OnInteractableButton3;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnInteractableButton1(InputAction.CallbackContext context);
        void OnInteractableButton2(InputAction.CallbackContext context);
        void OnInteractableButton3(InputAction.CallbackContext context);
    }
}
